
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS AUTHOR BEGIN DOC END ITEM ITEMIZE LB RB SECTION SUBSECTION TEXT TITLEdoc : BEGIN LB DOC RB content END LB DOC RBcontent : title abs sections\n                | title author abs sectionstitle : TITLE LB TEXT RB author : AUTHOR LB TEXT RBabs : BEGIN LB ABS RB TEXT END LB ABS RBsections : sections section\n                | sectionsection : SECTION LB TEXT RB TEXT\n                | section itemize\n                | section subsectionssubsections : subsections subsection\n                | subsectionsubsection : SUBSECTION LB TEXT RB TEXT\n                    | subsection itemize itemize : BEGIN LB ITEMIZE RB items END LB ITEMIZE RB\n                | BEGIN LB ITEMIZE RB itemize END LB ITEMIZE RBitems : item\n            | items itemitem : ITEM TEXT'
    
_lr_action_items = {'BEGIN':([0,7,11,17,24,25,26,28,34,36,38,42,47,49,55,67,68,],[2,12,12,27,27,-10,-11,27,-4,27,-15,-5,27,-9,-14,-16,-17,]),'$end':([1,35,],[0,-1,]),'LB':([2,8,9,12,13,18,27,29,50,57,59,],[3,14,15,20,21,30,37,39,56,62,63,]),'DOC':([3,15,],[4,23,]),'RB':([4,22,23,32,33,40,43,44,61,65,66,],[5,34,35,41,42,45,47,48,64,67,68,]),'TITLE':([5,],[8,]),'END':([6,16,17,24,25,26,28,31,36,38,46,49,51,52,53,55,58,60,67,68,],[9,-2,-8,-7,-10,-11,-13,-3,-12,-15,50,-9,57,59,-18,-14,-19,-20,-16,-17,]),'AUTHOR':([7,34,],[13,-4,]),'SECTION':([10,16,17,19,24,25,26,28,31,36,38,49,55,64,67,68,],[18,18,-8,18,-7,-10,-11,-13,18,-12,-15,-9,-14,-6,-16,-17,]),'TEXT':([14,21,30,39,41,45,48,54,],[22,33,40,44,46,49,55,60,]),'SUBSECTION':([17,24,25,26,28,36,38,49,55,67,68,],[29,29,-10,29,-13,-12,-15,-9,-14,-16,-17,]),'ABS':([20,56,],[32,61,]),'ITEMIZE':([37,62,63,],[43,65,66,]),'ITEM':([47,51,53,58,60,],[54,54,-18,-19,-20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'doc':([0,],[1,]),'content':([5,],[6,]),'title':([5,],[7,]),'abs':([7,11,],[10,19,]),'author':([7,],[11,]),'sections':([10,19,],[16,31,]),'section':([10,16,19,31,],[17,24,17,24,]),'itemize':([17,24,28,36,47,],[25,25,38,38,52,]),'subsections':([17,24,],[26,26,]),'subsection':([17,24,26,],[28,28,36,]),'items':([47,],[51,]),'item':([47,51,],[53,58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doc","S'",1,None,None,None),
  ('doc -> BEGIN LB DOC RB content END LB DOC RB','doc',9,'p_doc','parser.py',168),
  ('content -> title abs sections','content',3,'p_content','parser.py',174),
  ('content -> title author abs sections','content',4,'p_content','parser.py',175),
  ('title -> TITLE LB TEXT RB','title',4,'p_title','parser.py',190),
  ('author -> AUTHOR LB TEXT RB','author',4,'p_author','parser.py',196),
  ('abs -> BEGIN LB ABS RB TEXT END LB ABS RB','abs',9,'p_abs','parser.py',202),
  ('sections -> sections section','sections',2,'p_sections','parser.py',208),
  ('sections -> section','sections',1,'p_sections','parser.py',209),
  ('section -> SECTION LB TEXT RB TEXT','section',5,'p_section','parser.py',218),
  ('section -> section itemize','section',2,'p_section','parser.py',219),
  ('section -> section subsections','section',2,'p_section','parser.py',220),
  ('subsections -> subsections subsection','subsections',2,'p_subsections','parser.py',229),
  ('subsections -> subsection','subsections',1,'p_subsections','parser.py',230),
  ('subsection -> SUBSECTION LB TEXT RB TEXT','subsection',5,'p_subsection','parser.py',239),
  ('subsection -> subsection itemize','subsection',2,'p_subsection','parser.py',240),
  ('itemize -> BEGIN LB ITEMIZE RB items END LB ITEMIZE RB','itemize',9,'p_itemize','parser.py',253),
  ('itemize -> BEGIN LB ITEMIZE RB itemize END LB ITEMIZE RB','itemize',9,'p_itemize','parser.py',254),
  ('items -> item','items',1,'p_items','parser.py',259),
  ('items -> items item','items',2,'p_items','parser.py',260),
  ('item -> ITEM TEXT','item',2,'p_item','parser.py',269),
]
